### ISSUE TITLE
Hi, i have some error when build, can you help me?

### ISSUE THREAD

**Issue by pierreneter** [xBuyax/xanadu#1]
When i build this source, my vs console said:

`1>c:\xxx\xanadu\xanadu\xanadu\world.hpp(10): fatal error C1083: Cannot open include file: 'Poco\Data\Session.h': No such file or directory (compiling source file item_data_provider.cpp)`

**Comment by pierreneter** [comment]
oh. i think i must include Poco lib for this source. this's first time i build a C++ project. hm. Sorry if i annoy you.

**Comment by xBuyax** [comment]
Hello,

yes, Poco is used, specifically the libraries Foundation, Data and MySQL from it.
I use it to interact with mysql.

No problems, it isn't easy at the beginning to set it up.

I will create a tutorial thread at RageZone, also.

Greetings

Buya

**Comment by xBuyax** [comment]
Hi,

I close this now, if there is anything create a new issue or post in the ragezone thread or PM me there.

Greetings

Buya
