### ISSUE TITLE
[Minor Issue] Skill list doesn't update immediately

### ISSUE THREAD

**Issue by imbawind** [xBuyax/xanadu#11]
Skill doesn't update with new skills immediately after job advance.

**Comment by xBuyax** [comment]
Hi,

could you specify this in more detail?

**Comment by imbawind** [comment]
Like by default you press K and talk to the job advancer to have your job advanced, the Skill window doesn't update with new job's skill automatically, have to reopen the Skill window by pressing K to close and K again to open.

**Comment by xBuyax** [comment]
Actually I am not sure if that is a bug, the client handles to switch in the skill tab for the new job internally.
Unless there is a packet related to changing the job which refreshes the skill that automatically, this isn't a bug.

**Comment by xBuyax** [comment]
Hi,

after checking other repacks/source also, I am sure that this isn't a bug.
Maybe in later versions they added automatic skill tab refresh if it's open already.
I am not aware of any packet for that.

Therefore I close this.

Greetings

Buya

**Comment by imbawind** [comment]
True, I confirm this in some V62 JAVA based source.
