### ISSUE TITLE
[Bug] Seems like Gachapon doesn't check if player have enough slot for possible reward

### ISSUE THREAD

**Issue by imbawind** [xBuyax/xanadu#12]

**Comment by xBuyax** [comment]
Hi,

the give_item function gives item only if there is atleast one free slot, but it might be true that it isn't checked if the function was successfull, i will look into it.

**Comment by imbawind** [comment]
But the gachapon ticket is already -1 right?

**Comment by xBuyax** [comment]
Hi,

I just commited changes to gachapon, it should now check if the item could be added, if not, it says a text, if yes, it also removes one ticket.

You may look at my commit and comment if you think it's solved well and test gachapon also if you want, I leave this open a bit.

**Comment by xBuyax** [comment]
Well whatever, I close this as it's fixed apparently.
