### ISSUE TITLE
Auto recovery hp mp bug?

### ISSUE THREAD

**Issue by kurokami98** [xBuyax/xanadu#18]
It seems the auto hp mp recovery is bugged. The heal value is not correct and will get huge amount of heal value and instant full health.

**Comment by kurokami98** [comment]
Well, just change the skip_bytes(4) to skip_bytes(8) and it's fixed.

**Comment by xBuyax** [comment]
thank you for this hint, i fixed it. indeed it was 4 extra bytes like you said
