### ISSUE TITLE
is Xanadu possibility to latest gms or 176.1 ?

### ISSUE THREAD

**Issue by Mellowz** [xBuyax/xanadu#19]
because i saw in a ragezone forum has localhost.exe for v176.1, is that possible to use with Xanadu ?

And another question, is Xanadu can be compile and run in linux (ubuntu) ?

**Comment by xBuyax** [comment]
Hi,
no, it's made for GMS v0.83.

Also, it is currently not ready to be used for any linux operating system.
It would require build files and some adjustments/cross platform compability is required for all third party libraries also, in order for it to work.
