### ISSUE TITLE
Job advance

### ISSUE THREAD

**Issue by imbawind** [xBuyax/xanadu#2]
Couldn't from 3rd job to 4th job for mage( IL at least), even GM command didn't work.
**I used a modified !levelup(that loop the levelup function as many as I want) instead of !level as the latter one only chg the level variable, didnt really 'level up' the char. After reaching required level then go press the npc.

***Tested other class, also do not work.

****EDIT****
So now I think this is probably a bug: [For magician at least]
Level to 30, talk to job advancer, nothing come out, have to relog then talk to him again then only I advance to 2nd job. Then I use command to 70 level, talk to job advancer, advanced successfully to 3rd Job. Used command again to 120 level, talk to job advancer, no response again and have to relog to fix the problem. Not a really serious bug but rather a annoying one.

Previous tested character which didnt work(no response) even GM command is used, after relog they all have their job changed to what I typed(GM command) just now.

**Comment by xBuyax** [comment]
Hello,

thanks for reporting. I will soon investigate this and the job advancers and then come back.

Greetings

Buya

**Comment by xBuyax** [comment]
Hi,

I want to inform you that currently GMS-like job advancement is not available.

Currently the standard-job-advancer npcs for the basis jobs mage, bowman, thief, warrior and pirate do all job advancements when the specific levels are reached.

Other than that there might be stuck issues with npc's, I will soon check that and fix it if that's true.

Greetings

Buya

**Comment by xBuyax** [comment]
Hello,

I just made a commit that should fix the stuck bugs that you were apparently experiencing with the job advancer npc's.

I will test it, but please test and confirm it yourself and write here if it has been fixed now.

Greetings

Buya

**Comment by imbawind** [comment]
Hi, thanks for your replies, it's already wee hour here in my place so I will test it tomorrow.
I wanted to add dialogs for NPCs(GMS-like) but failed to do so as there's no any dialog that's more than 2 state of conversation that I can use as reference. I've tried to use those send_next thing but seems like the state counter didn't increment or I did something totally wrong. (I was trying to code Spinel, also I'm not sure what function can be used to store user previous map_id)
I also tried to code Sera but when I link script to outside I get a compile error which I'm not able to solve, write the code directly in the file where all other NPCs sit works tho, but not a neat way to do so.

**Comment by xBuyax** [comment]
Hi,

due to the way it's currently handled, when an npc does not send one or more texts, a different state than 0 is needed, I use high numbers for it like 1000. So yes it is a magic number. Otherwise it stucks because when talking to an npc, it needs to check if there is already a conversation.

spinel can be done like this (put that code into a function, should work):

http://pastebin.com/2yQLUhng

Greetings

Buya

**Comment by imbawind** [comment]
Hi, these function work if I code them into player.cpp directly but if I want to code them in an external file(by adding a handle eg:handle_npc_lmpq_rolly3();) then I'll not be able to compile, I did included the added files in player.hpp, what could be the problem?

**Comment by xBuyax** [comment]
Hi,

you don't have to put it into player.cpp, you can use an existing or a new .cpp file. it needs to be declared in player.hpp and defined in that file. what is the error you get?

**Comment by xBuyax** [comment]
Hi,

if you still have questions such as just stated in your last post, please create a new issue or by private message or by a post on ragezone.

The original issue has been fixed.
