### ISSUE TITLE
Bowmaster Hurricane

### ISSUE THREAD

**Issue by imbawind** [xBuyax/xanadu#5]
Bowmaster's Hurricane skill hurt mobs but doesn't kill them.

**Comment by xBuyax** [comment]
Hi,

thanks for reporting, I will investigate this soon.

**Comment by xBuyax** [comment]
Hi, I just confirmed this and I will further investigate and if possible quickly fix it.

**Comment by xBuyax** [comment]
Hi, I just commited changes that should fix it, can you confirm it?

**Comment by xBuyax** [comment]
EDIT: It is defenitely fixed, therefore I close this.

Thank you for your report.
