### ISSUE TITLE
Regular cab not working

### ISSUE THREAD

**Issue by imbawind** [xBuyax/xanadu#7]
Regular cab only respond in Henesys, doesn't respond in Perion/Kerning/Ellinia.
Tried to add a else block and put magic state inside, didn't work.

**Comment by imbawind** [comment]
Fixed. 
Hope my pull request done properly.

**Comment by xBuyax** [comment]
Hi,

your report is correct, npc's weren't much worked on yet.
I will soon review your proposed fix.

Greetings

Buya

**Comment by xBuyax** [comment]
Hi,

I tested how it is now, it appears to be fixed with your changes.
Therefore I close this.

Greetings

Buya
