### ISSUE TITLE
[Bug] Scroll not working

### ISSUE THREAD

**Issue by imbawind** [xBuyax/xanadu#9]
Even 100% scroll fail.

**Comment by xBuyax** [comment]
Hi,

I will soon investigate this.
Is the bug only about scrolls failing?

**Comment by imbawind** [comment]
Yeah, currently.

**Comment by xBuyax** [comment]
Hi,
I confirmed it and found the issue: a code mistake in item data loading caused this, scrolls and maybe more wasn't loaded (properly).

I just commited a fix and to my tests scrolls work now.

Can you confirm this? I ask because this is a huge issue so I rather get confirmation.

**Comment by imbawind** [comment]
Used gm command to make some scroll for magic att., seems to be working, some scrolls succeed, some scrolls failed.

**Comment by xBuyax** [comment]
Ok, so now that it's fixed, I close this.
